export const Users = [
    {
        id: 1,
        profilePicture: "assets/person/chadmichaels.jpeg",
        username: "Chad Michaels",
    },
    {
        id: 2,
        profilePicture: "assets/person/alyssaedwards.jpeg",
        username: "Alyssa Edwards",
    },
    {
        id: 3,
        profilePicture: "assets/person/katya.jpeg",
        username: "Katy Zamolodchikova",
    },
    {
        id: 4,
        profilePicture: "assets/person/adoredelano.jpeg",
        username: "Adore Delano",
    },
    {
        id: 5,
        profilePicture: "assets/person/zohan.jpeg",
        username: "Scrappy Coco",
    },
    {
        id: 6,
        profilePicture: "assets/person/detox.jpeg",
        username: "Detox",
    },
    {
        id: 7,
        profilePicture: "assets/person/latriceroyale.jpeg",
        username: "Latrice Royale",
    },
    {
        id: 8,
        profilePicture: "assets/person/alaska.jpeg",
        username: "Alaska Thunderfuck 300",
    },
    {
        id: 9,
        profilePicture: "assets/person/bradpitt.jpeg",
        username: "William Bradley Pitt",
    },
    {
        id: 10,
        profilePicture: "assets/person/shangela.jpeg",
        username: "Shangela Laquifa Wadley",
    },
];

export const Posts = [
    {
        id: 1,
        desc: "I'm Cher BITCH!",
        photo: "assets/post/one.jpeg",
        date: "2 minutes ago",
        userId: 1,
        like: 9,
        comment: 2,
    },
    {
        id: 2,
        desc: "I don't get cute, I get drop dead gorgeous",
        photo: "assets/post/two.jpeg",
        date: "9 minutes ago",
        userId: 2,
        like: 18,
        comment:2,
    },
    {
        id: 3,
        desc: "Lenin in the streets, Dostoyevsky in the sheets",
        photo: "assets/post/three.jpeg",
        date: "18 minutes ago",
        userId: 1,
        like: 47,
        comment: 9,
    },
    {
        id: 4,
        desc: "I'm fucking hood, I'm from Azusa I'll stab a bitch",
        photo: "assets/post/four.jpeg",
        date: "36 minutes ago",
        userId: 4,
        like: 69,
        comment: 18,
    },
    {
        id: 5,
        desc: "I just want to make hair silky-smooth",
        photo: "assets/post/five.jpeg",
        date: "47 minutes ago",
        userId: 5,
        like: 74,
        comment: 19,
    },
    {
        id: 6,
        desc: "Detox comin' at you with the slow verse",
        photo: "assets/post/six.jpeg",
        date: "1 hour ago",
        userId: 6,
        like: 92,
        comment: 20,
    },
    {
        id: 7,
        desc: "Good god get a grip girl",
        photo: "assets/post/seven.jpeg",
        date: "1 hour ago",
        userId: 7,
        like: 111,
        comment: 24,
    },
    {
        id: 8,
        desc: "Cause you're gonna see me hangin' in the hall of fame!",
        photo: "assets/post/eight.jpeg",
        date: "1 hour ago",
        userId: 8,
        like: 112,
        comment: 19,
    },
    {
        id: 9,
        desc: "You probably heard we ain't in the prisoner-takin' business; we in the killin' Nazi business. And cousin, business is a-boomin'",
        photo: "assets/post/nine.jpeg",
        date: "1 hour ago",
        userId: 9,
        like: 147,
        comment: 31,
    },
    {
        id: 10,
        desc: "Halleloo!",
        photo: "assets/post/ten.jpeg",
        date: "2 hours ago",
        userId: 10,
        like: 189,
        comment: 21,
    },
];